PLAYGROUND_WIDTH = 800
PLAYGROUND_HEIGHT = 600
WINDOW_WIDTH = PLAYGROUND_WIDTH + 200
WINDOW_HEIGHT = 600
BLOCK_SIZE = 6
CELL_ENERGY_START = 100 # Количество энергии первоначальных клеток при создании мира

CELL_ENERGY_MAX = 1500
CELL_ENERGY_MAX_PHOTOSYNTHETIC = 800
CELL_ENERGY_MAX_PREDATOR = 1000

PHOTOSYNTHESIS_ENERGY = 10
MOVEMENT_COST = 8
REPRODUCTION_THRESHOLD = 250
FPS = 120
